# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://github.com/rubocop-hq/rubocop/blob/master/manual/configuration.md

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
  - 'spec/**/*'
  - 'Rakefile'
  - 'app_info.gemspec'
  - 'lib/app-info.rb'

Metrics/AbcSize:
  Max: 100

Metrics/BlockLength:
  Max: 35

Metrics/MethodLength:
  Max: 20

Metrics/LineLength:
  Max: 100

Metrics/ClassLength:
  CountComments: false
  Max: 300

Metrics/CyclomaticComplexity:
  Max: 10


Style/Documentation:
  Enabled: false
