# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/Configuration.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("proto/Configuration.proto", :syntax => :proto3) do
    add_message "aapt.pb.Configuration" do
      optional :mcc, :uint32, 1
      optional :mnc, :uint32, 2
      optional :locale, :string, 3
      optional :layout_direction, :enum, 4, "aapt.pb.Configuration.LayoutDirection"
      optional :screen_width, :uint32, 5
      optional :screen_height, :uint32, 6
      optional :screen_width_dp, :uint32, 7
      optional :screen_height_dp, :uint32, 8
      optional :smallest_screen_width_dp, :uint32, 9
      optional :screen_layout_size, :enum, 10, "aapt.pb.Configuration.ScreenLayoutSize"
      optional :screen_layout_long, :enum, 11, "aapt.pb.Configuration.ScreenLayoutLong"
      optional :screen_round, :enum, 12, "aapt.pb.Configuration.ScreenRound"
      optional :wide_color_gamut, :enum, 13, "aapt.pb.Configuration.WideColorGamut"
      optional :hdr, :enum, 14, "aapt.pb.Configuration.Hdr"
      optional :orientation, :enum, 15, "aapt.pb.Configuration.Orientation"
      optional :ui_mode_type, :enum, 16, "aapt.pb.Configuration.UiModeType"
      optional :ui_mode_night, :enum, 17, "aapt.pb.Configuration.UiModeNight"
      optional :density, :uint32, 18
      optional :touchscreen, :enum, 19, "aapt.pb.Configuration.Touchscreen"
      optional :keys_hidden, :enum, 20, "aapt.pb.Configuration.KeysHidden"
      optional :keyboard, :enum, 21, "aapt.pb.Configuration.Keyboard"
      optional :nav_hidden, :enum, 22, "aapt.pb.Configuration.NavHidden"
      optional :navigation, :enum, 23, "aapt.pb.Configuration.Navigation"
      optional :sdk_version, :uint32, 24
      optional :product, :string, 25
    end
    add_enum "aapt.pb.Configuration.LayoutDirection" do
      value :LAYOUT_DIRECTION_UNSET, 0
      value :LAYOUT_DIRECTION_LTR, 1
      value :LAYOUT_DIRECTION_RTL, 2
    end
    add_enum "aapt.pb.Configuration.ScreenLayoutSize" do
      value :SCREEN_LAYOUT_SIZE_UNSET, 0
      value :SCREEN_LAYOUT_SIZE_SMALL, 1
      value :SCREEN_LAYOUT_SIZE_NORMAL, 2
      value :SCREEN_LAYOUT_SIZE_LARGE, 3
      value :SCREEN_LAYOUT_SIZE_XLARGE, 4
    end
    add_enum "aapt.pb.Configuration.ScreenLayoutLong" do
      value :SCREEN_LAYOUT_LONG_UNSET, 0
      value :SCREEN_LAYOUT_LONG_LONG, 1
      value :SCREEN_LAYOUT_LONG_NOTLONG, 2
    end
    add_enum "aapt.pb.Configuration.ScreenRound" do
      value :SCREEN_ROUND_UNSET, 0
      value :SCREEN_ROUND_ROUND, 1
      value :SCREEN_ROUND_NOTROUND, 2
    end
    add_enum "aapt.pb.Configuration.WideColorGamut" do
      value :WIDE_COLOR_GAMUT_UNSET, 0
      value :WIDE_COLOR_GAMUT_WIDECG, 1
      value :WIDE_COLOR_GAMUT_NOWIDECG, 2
    end
    add_enum "aapt.pb.Configuration.Hdr" do
      value :HDR_UNSET, 0
      value :HDR_HIGHDR, 1
      value :HDR_LOWDR, 2
    end
    add_enum "aapt.pb.Configuration.Orientation" do
      value :ORIENTATION_UNSET, 0
      value :ORIENTATION_PORT, 1
      value :ORIENTATION_LAND, 2
      value :ORIENTATION_SQUARE, 3
    end
    add_enum "aapt.pb.Configuration.UiModeType" do
      value :UI_MODE_TYPE_UNSET, 0
      value :UI_MODE_TYPE_NORMAL, 1
      value :UI_MODE_TYPE_DESK, 2
      value :UI_MODE_TYPE_CAR, 3
      value :UI_MODE_TYPE_TELEVISION, 4
      value :UI_MODE_TYPE_APPLIANCE, 5
      value :UI_MODE_TYPE_WATCH, 6
      value :UI_MODE_TYPE_VRHEADSET, 7
    end
    add_enum "aapt.pb.Configuration.UiModeNight" do
      value :UI_MODE_NIGHT_UNSET, 0
      value :UI_MODE_NIGHT_NIGHT, 1
      value :UI_MODE_NIGHT_NOTNIGHT, 2
    end
    add_enum "aapt.pb.Configuration.Touchscreen" do
      value :TOUCHSCREEN_UNSET, 0
      value :TOUCHSCREEN_NOTOUCH, 1
      value :TOUCHSCREEN_STYLUS, 2
      value :TOUCHSCREEN_FINGER, 3
    end
    add_enum "aapt.pb.Configuration.KeysHidden" do
      value :KEYS_HIDDEN_UNSET, 0
      value :KEYS_HIDDEN_KEYSEXPOSED, 1
      value :KEYS_HIDDEN_KEYSHIDDEN, 2
      value :KEYS_HIDDEN_KEYSSOFT, 3
    end
    add_enum "aapt.pb.Configuration.Keyboard" do
      value :KEYBOARD_UNSET, 0
      value :KEYBOARD_NOKEYS, 1
      value :KEYBOARD_QWERTY, 2
      value :KEYBOARD_TWELVEKEY, 3
    end
    add_enum "aapt.pb.Configuration.NavHidden" do
      value :NAV_HIDDEN_UNSET, 0
      value :NAV_HIDDEN_NAVEXPOSED, 1
      value :NAV_HIDDEN_NAVHIDDEN, 2
    end
    add_enum "aapt.pb.Configuration.Navigation" do
      value :NAVIGATION_UNSET, 0
      value :NAVIGATION_NONAV, 1
      value :NAVIGATION_DPAD, 2
      value :NAVIGATION_TRACKBALL, 3
      value :NAVIGATION_WHEEL, 4
    end
  end
end

module Aapt
  module Pb
    Configuration = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.Configuration").msgclass
    Configuration::LayoutDirection = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.Configuration.LayoutDirection").enummodule
    Configuration::ScreenLayoutSize = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.Configuration.ScreenLayoutSize").enummodule
    Configuration::ScreenLayoutLong = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.Configuration.ScreenLayoutLong").enummodule
    Configuration::ScreenRound = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.Configuration.ScreenRound").enummodule
    Configuration::WideColorGamut = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.Configuration.WideColorGamut").enummodule
    Configuration::Hdr = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.Configuration.Hdr").enummodule
    Configuration::Orientation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.Configuration.Orientation").enummodule
    Configuration::UiModeType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.Configuration.UiModeType").enummodule
    Configuration::UiModeNight = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.Configuration.UiModeNight").enummodule
    Configuration::Touchscreen = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.Configuration.Touchscreen").enummodule
    Configuration::KeysHidden = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.Configuration.KeysHidden").enummodule
    Configuration::Keyboard = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.Configuration.Keyboard").enummodule
    Configuration::NavHidden = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.Configuration.NavHidden").enummodule
    Configuration::Navigation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.Configuration.Navigation").enummodule
  end
end
