# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Resources.proto

require 'google/protobuf'
require 'app_info/aab/proto/Configuration_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("Resources.proto", :syntax => :proto3) do
    add_message "aapt.pb.StringPool" do
      optional :data, :bytes, 1
    end
    add_message "aapt.pb.SourcePosition" do
      optional :line_number, :uint32, 1
      optional :column_number, :uint32, 2
    end
    add_message "aapt.pb.Source" do
      optional :path_idx, :uint32, 1
      optional :position, :message, 2, "aapt.pb.SourcePosition"
    end
    add_message "aapt.pb.ToolFingerprint" do
      optional :tool, :string, 1
      optional :version, :string, 2
    end
    add_message "aapt.pb.ResourceTable" do
      optional :source_pool, :message, 1, "aapt.pb.StringPool"
      repeated :package, :message, 2, "aapt.pb.Package"
      repeated :overlayable, :message, 3, "aapt.pb.Overlayable"
      repeated :tool_fingerprint, :message, 4, "aapt.pb.ToolFingerprint"
    end
    add_message "aapt.pb.PackageId" do
      optional :id, :uint32, 1
    end
    add_message "aapt.pb.Package" do
      optional :package_id, :message, 1, "aapt.pb.PackageId"
      optional :package_name, :string, 2
      repeated :type, :message, 3, "aapt.pb.Type"
    end
    add_message "aapt.pb.TypeId" do
      optional :id, :uint32, 1
    end
    add_message "aapt.pb.Type" do
      optional :type_id, :message, 1, "aapt.pb.TypeId"
      optional :name, :string, 2
      repeated :entry, :message, 3, "aapt.pb.Entry"
    end
    add_message "aapt.pb.Visibility" do
      optional :level, :enum, 1, "aapt.pb.Visibility.Level"
      optional :source, :message, 2, "aapt.pb.Source"
      optional :comment, :string, 3
    end
    add_enum "aapt.pb.Visibility.Level" do
      value :UNKNOWN, 0
      value :PRIVATE, 1
      value :PUBLIC, 2
    end
    add_message "aapt.pb.AllowNew" do
      optional :source, :message, 1, "aapt.pb.Source"
      optional :comment, :string, 2
    end
    add_message "aapt.pb.Overlayable" do
      optional :name, :string, 1
      optional :source, :message, 2, "aapt.pb.Source"
      optional :actor, :string, 3
    end
    add_message "aapt.pb.OverlayableItem" do
      optional :source, :message, 1, "aapt.pb.Source"
      optional :comment, :string, 2
      repeated :policy, :enum, 3, "aapt.pb.OverlayableItem.Policy"
      optional :overlayable_idx, :uint32, 4
    end
    add_enum "aapt.pb.OverlayableItem.Policy" do
      value :NONE, 0
      value :PUBLIC, 1
      value :SYSTEM, 2
      value :VENDOR, 3
      value :PRODUCT, 4
      value :SIGNATURE, 5
      value :ODM, 6
      value :OEM, 7
      value :ACTOR, 8
      value :CONFIG_SIGNATURE, 9
    end
    add_message "aapt.pb.EntryId" do
      optional :id, :uint32, 1
    end
    add_message "aapt.pb.Entry" do
      optional :entry_id, :message, 1, "aapt.pb.EntryId"
      optional :name, :string, 2
      optional :visibility, :message, 3, "aapt.pb.Visibility"
      optional :allow_new, :message, 4, "aapt.pb.AllowNew"
      optional :overlayable_item, :message, 5, "aapt.pb.OverlayableItem"
      repeated :config_value, :message, 6, "aapt.pb.ConfigValue"
    end
    add_message "aapt.pb.ConfigValue" do
      optional :config, :message, 1, "aapt.pb.Configuration"
      optional :value, :message, 2, "aapt.pb.Value"
    end
    add_message "aapt.pb.Value" do
      optional :source, :message, 1, "aapt.pb.Source"
      optional :comment, :string, 2
      optional :weak, :bool, 3
      oneof :value do
        optional :item, :message, 4, "aapt.pb.Item"
        optional :compound_value, :message, 5, "aapt.pb.CompoundValue"
      end
    end
    add_message "aapt.pb.Item" do
      oneof :value do
        optional :ref, :message, 1, "aapt.pb.Reference"
        optional :str, :message, 2, "aapt.pb.String"
        optional :raw_str, :message, 3, "aapt.pb.RawString"
        optional :styled_str, :message, 4, "aapt.pb.StyledString"
        optional :file, :message, 5, "aapt.pb.FileReference"
        optional :id, :message, 6, "aapt.pb.Id"
        optional :prim, :message, 7, "aapt.pb.Primitive"
      end
    end
    add_message "aapt.pb.CompoundValue" do
      oneof :value do
        optional :attr, :message, 1, "aapt.pb.Attribute"
        optional :style, :message, 2, "aapt.pb.Style"
        optional :styleable, :message, 3, "aapt.pb.Styleable"
        optional :array, :message, 4, "aapt.pb.Array"
        optional :plural, :message, 5, "aapt.pb.Plural"
      end
    end
    add_message "aapt.pb.Boolean" do
      optional :value, :bool, 1
    end
    add_message "aapt.pb.Reference" do
      optional :type, :enum, 1, "aapt.pb.Reference.Type"
      optional :id, :uint32, 2
      optional :name, :string, 3
      optional :private, :bool, 4
      optional :is_dynamic, :message, 5, "aapt.pb.Boolean"
    end
    add_enum "aapt.pb.Reference.Type" do
      value :REFERENCE, 0
      value :ATTRIBUTE, 1
    end
    add_message "aapt.pb.Id" do
    end
    add_message "aapt.pb.String" do
      optional :value, :string, 1
    end
    add_message "aapt.pb.RawString" do
      optional :value, :string, 1
    end
    add_message "aapt.pb.StyledString" do
      optional :value, :string, 1
      repeated :span, :message, 2, "aapt.pb.StyledString.Span"
    end
    add_message "aapt.pb.StyledString.Span" do
      optional :tag, :string, 1
      optional :first_char, :uint32, 2
      optional :last_char, :uint32, 3
    end
    add_message "aapt.pb.FileReference" do
      optional :path, :string, 1
      optional :type, :enum, 2, "aapt.pb.FileReference.Type"
    end
    add_enum "aapt.pb.FileReference.Type" do
      value :UNKNOWN, 0
      value :PNG, 1
      value :BINARY_XML, 2
      value :PROTO_XML, 3
    end
    add_message "aapt.pb.Primitive" do
      oneof :oneof_value do
        optional :null_value, :message, 1, "aapt.pb.Primitive.NullType"
        optional :empty_value, :message, 2, "aapt.pb.Primitive.EmptyType"
        optional :float_value, :float, 3
        optional :dimension_value, :uint32, 13
        optional :fraction_value, :uint32, 14
        optional :int_decimal_value, :int32, 6
        optional :int_hexadecimal_value, :uint32, 7
        optional :boolean_value, :bool, 8
        optional :color_argb8_value, :uint32, 9
        optional :color_rgb8_value, :uint32, 10
        optional :color_argb4_value, :uint32, 11
        optional :color_rgb4_value, :uint32, 12
        optional :dimension_value_deprecated, :float, 4
        optional :fraction_value_deprecated, :float, 5
      end
    end
    add_message "aapt.pb.Primitive.NullType" do
    end
    add_message "aapt.pb.Primitive.EmptyType" do
    end
    add_message "aapt.pb.Attribute" do
      optional :format_flags, :uint32, 1
      optional :min_int, :int32, 2
      optional :max_int, :int32, 3
      repeated :symbol, :message, 4, "aapt.pb.Attribute.Symbol"
    end
    add_message "aapt.pb.Attribute.Symbol" do
      optional :source, :message, 1, "aapt.pb.Source"
      optional :comment, :string, 2
      optional :name, :message, 3, "aapt.pb.Reference"
      optional :value, :uint32, 4
      optional :type, :uint32, 5
    end
    add_enum "aapt.pb.Attribute.FormatFlags" do
      value :NONE, 0
      value :ANY, 65535
      value :REFERENCE, 1
      value :STRING, 2
      value :INTEGER, 4
      value :BOOLEAN, 8
      value :COLOR, 16
      value :FLOAT, 32
      value :DIMENSION, 64
      value :FRACTION, 128
      value :ENUM, 65536
      value :FLAGS, 131072
    end
    add_message "aapt.pb.Style" do
      optional :parent, :message, 1, "aapt.pb.Reference"
      optional :parent_source, :message, 2, "aapt.pb.Source"
      repeated :entry, :message, 3, "aapt.pb.Style.Entry"
    end
    add_message "aapt.pb.Style.Entry" do
      optional :source, :message, 1, "aapt.pb.Source"
      optional :comment, :string, 2
      optional :key, :message, 3, "aapt.pb.Reference"
      optional :item, :message, 4, "aapt.pb.Item"
    end
    add_message "aapt.pb.Styleable" do
      repeated :entry, :message, 1, "aapt.pb.Styleable.Entry"
    end
    add_message "aapt.pb.Styleable.Entry" do
      optional :source, :message, 1, "aapt.pb.Source"
      optional :comment, :string, 2
      optional :attr, :message, 3, "aapt.pb.Reference"
    end
    add_message "aapt.pb.Array" do
      repeated :element, :message, 1, "aapt.pb.Array.Element"
    end
    add_message "aapt.pb.Array.Element" do
      optional :source, :message, 1, "aapt.pb.Source"
      optional :comment, :string, 2
      optional :item, :message, 3, "aapt.pb.Item"
    end
    add_message "aapt.pb.Plural" do
      repeated :entry, :message, 1, "aapt.pb.Plural.Entry"
    end
    add_message "aapt.pb.Plural.Entry" do
      optional :source, :message, 1, "aapt.pb.Source"
      optional :comment, :string, 2
      optional :arity, :enum, 3, "aapt.pb.Plural.Arity"
      optional :item, :message, 4, "aapt.pb.Item"
    end
    add_enum "aapt.pb.Plural.Arity" do
      value :ZERO, 0
      value :ONE, 1
      value :TWO, 2
      value :FEW, 3
      value :MANY, 4
      value :OTHER, 5
    end
    add_message "aapt.pb.XmlNode" do
      optional :source, :message, 3, "aapt.pb.SourcePosition"
      oneof :node do
        optional :element, :message, 1, "aapt.pb.XmlElement"
        optional :text, :string, 2
      end
    end
    add_message "aapt.pb.XmlElement" do
      repeated :namespace_declaration, :message, 1, "aapt.pb.XmlNamespace"
      optional :namespace_uri, :string, 2
      optional :name, :string, 3
      repeated :attribute, :message, 4, "aapt.pb.XmlAttribute"
      repeated :child, :message, 5, "aapt.pb.XmlNode"
    end
    add_message "aapt.pb.XmlNamespace" do
      optional :prefix, :string, 1
      optional :uri, :string, 2
      optional :source, :message, 3, "aapt.pb.SourcePosition"
    end
    add_message "aapt.pb.XmlAttribute" do
      optional :namespace_uri, :string, 1
      optional :name, :string, 2
      optional :value, :string, 3
      optional :source, :message, 4, "aapt.pb.SourcePosition"
      optional :resource_id, :uint32, 5
      optional :compiled_item, :message, 6, "aapt.pb.Item"
    end
  end
end

module Aapt
  module Pb
    StringPool = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.StringPool").msgclass
    SourcePosition = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.SourcePosition").msgclass
    Source = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.Source").msgclass
    ToolFingerprint = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.ToolFingerprint").msgclass
    ResourceTable = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.ResourceTable").msgclass
    PackageId = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.PackageId").msgclass
    Package = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.Package").msgclass
    TypeId = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.TypeId").msgclass
    Type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.Type").msgclass
    Visibility = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.Visibility").msgclass
    Visibility::Level = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.Visibility.Level").enummodule
    AllowNew = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.AllowNew").msgclass
    Overlayable = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.Overlayable").msgclass
    OverlayableItem = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.OverlayableItem").msgclass
    OverlayableItem::Policy = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.OverlayableItem.Policy").enummodule
    EntryId = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.EntryId").msgclass
    Entry = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.Entry").msgclass
    ConfigValue = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.ConfigValue").msgclass
    Value = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.Value").msgclass
    Item = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.Item").msgclass
    CompoundValue = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.CompoundValue").msgclass
    Boolean = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.Boolean").msgclass
    Reference = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.Reference").msgclass
    Reference::Type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.Reference.Type").enummodule
    Id = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.Id").msgclass
    String = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.String").msgclass
    RawString = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.RawString").msgclass
    StyledString = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.StyledString").msgclass
    StyledString::Span = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.StyledString.Span").msgclass
    FileReference = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.FileReference").msgclass
    FileReference::Type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.FileReference.Type").enummodule
    Primitive = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.Primitive").msgclass
    Primitive::NullType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.Primitive.NullType").msgclass
    Primitive::EmptyType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.Primitive.EmptyType").msgclass
    Attribute = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.Attribute").msgclass
    Attribute::Symbol = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.Attribute.Symbol").msgclass
    Attribute::FormatFlags = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.Attribute.FormatFlags").enummodule
    Style = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.Style").msgclass
    Style::Entry = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.Style.Entry").msgclass
    Styleable = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.Styleable").msgclass
    Styleable::Entry = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.Styleable.Entry").msgclass
    Array = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.Array").msgclass
    Array::Element = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.Array.Element").msgclass
    Plural = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.Plural").msgclass
    Plural::Entry = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.Plural.Entry").msgclass
    Plural::Arity = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.Plural.Arity").enummodule
    XmlNode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.XmlNode").msgclass
    XmlElement = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.XmlElement").msgclass
    XmlNamespace = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.XmlNamespace").msgclass
    XmlAttribute = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aapt.pb.XmlAttribute").msgclass
  end
end
